config/routes.rb
Rails.application.routes.draw do
  get 'error_template/index', as: "error"
  devise_for :users

  resources :events do
    resources :guests, only: [:new, :create, :show]
  end
   root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id         :integer          not null, primary key
#  name       :string
#  event_date :datetime
#  address    :string
#  capacity   :integer          default(0)
#  available  :boolean          default(TRUE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer          not null
#  progress   :integer          default(0)
#  message    :text
#
class Event < ApplicationRecord
   # where(available: false).paginate(page: params[:page], per_page: 6).order("id DESC")
   #where(available: true).where(event_date: current_date..(current_date + 10.days) )
   current_date = Date.today
    require 'date'
    #associations
    belongs_to :user
    has_many :guests, dependent: :destroy

    #validations
    validates :name, presence: true
    validates :address, presence: true 
    validates :event_date, presence: true
    #callbacks
    before_create :capitalize_name
    #broadcast Sockets
    after_commit {broadcast_refresh_to :events_list}
    after_commit {broadcast_refresh_to :event}
    #scopes
    scope :closed, -> {where(available: false)}
    scope :upcoming_events, ->{where(available: true).where(event_date: current_date..(current_date + 10.days) )}
    
    def format_date 
        if self.event_date
            parse_date = DateTime.parse(self.event_date.to_s)
            formated_date = parse_date.strftime("%e %^b  %Y")
            #EVENT_HOURS = parse_date.strftime("%H %M")

            return formated_date
        end 
    end
     def close_event
        current_time = Time.now 
        time_to_close = Date.parse(self.event_date.to_s) if self.event_date

        if !self.event_date  || current_time >= time_to_close  || self.capacity <= 0
            self.available = false
        else
            self.available = true
           
        end
        self.save
     end

     def calculate_progress(p = 0)
        participants = p.to_f
        porcentage = (participants / self.capacity) * 100
        if self.progress != 100 || self.capacity > 0
                self.progress += (porcentage.abs - self.progress)
                self.capacity -= participants
                self.save
        end
     end

     def return_progress 
        return self.progress
     end
     
     def return_status 
       if self.progress == 100 
         return "Event Full"
       elsif self.available == false 
        return "Closed"
       end
     end

     def return_total
        total = 0
        self.guests.each do |g|
            total += g.total
        end
        return total
     end

    def map_url
   
        parse_address = self.address.split(" ").join("+")

        return  "https://www.google.com/maps/dir/?api=1&destination=#{parse_address}"
    end

    def capitalize_name 
        self.name = self.name.capitalize
    end
end

app/models/guest.rb
# == Schema Information
#
# Table name: guests
#
#  id         :integer          not null, primary key
#  name       :string
#  companions :integer          default(0)
#  event_id   :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Guest < ApplicationRecord
  belongs_to :event
  before_create :set_total
after_create :call_event


private
  def call_event
     self.event.calculate_progress(self.total)
  end

  def set_total 
    self.total =  self.total = 1 + self.companions
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  name                   :string
#  last_name              :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         #validations
        before_create :capitalize_name
      has_many :events, dependent: :destroy
       


      def full_name 
         return "#{self.name} #{self.last_name}"
      end

      private 
      def capitalize_name 
         self.name = self.name.capitalize
         self.last_name = self.last_name.capitalize
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:last_name])
      devise_parameter_sanitizer.permit(:update, keys: [:name,:last_name])

    end
end

app/controllers/error_template_controller.rb
class ErrorTemplateController < ApplicationController
  def index
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy event_detail]
  before_action :authenticate_user!, except: %i[ show]

  # GET /events or /events.json
  def index
    @events
    Event.all.each do |e|
      e.close_event
    end
    if params[:opt]
      case params[:opt]
        when 'closed'
          @events = current_user.events.closed.paginate(page: params[:page], per_page: 6).order("id DESC")
        when 'upcoming'
          @events = current_user.events.upcoming_events.paginate(page: params[:page], per_page: 6).order("id DESC")
       
          
      else 
          @events = "Sorry, no Events found it"
      end
        #render "index"
    else
      @events = current_user.events.paginate(page: params[:page], per_page: 6).order(" id DESC")
    
    end
    
    return @events
    render "index"
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = current_user.events.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to root_path, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    @event.close_event
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to root_path, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy!

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  #custom functions
  def event_detail

  end

  private
    def set_event
     event = Event.find_by(id: params[:id])
     if event 
          return @event = event 
      else 
          redirect_to error_path
     end

    end
    def event_params
      params.require(:event).permit(:name, :event_date, :address, :capacity, :message)
    end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
before_action :find_event
def show 
   @guests = Guest.where(event_id: @event.id)
end
  def new 
    @guest= @event.guests.build
  end
  def create
    @guest = @event.guests.create(guest_params)
    
        redirect_to event_path(@event)
  end


  private 
  def find_event 
    @event = Event.find(params[:event_id])
  end 
  def guest_params 
    params.require(:guest).permit(:name, :companions)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_template_helper.rb
module ErrorTemplateHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/error_template/index.html.erb
<h1> Sorry,we cannot find the resource</h1>

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">

</div>

app/views/events/_form.html.erb
<div data-controller="hello">
<%= form_with(model: event,data: {action: "submit->hello#closeModal"}) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :event_date, style: "display: block" %>
    <%= form.datetime_field :event_date %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :capacity, style: "display: block" %>
    <%= form.number_field :capacity %>
  </div>

  <div>
    <%= form.label :available, style: "display: block" %>
    <%= form.check_box :available %>
  </div>

  <div>
    <%= form.submit%>
  </div>
<% end %>
</div>

app/views/events/edit.html.erb
<%=turbo_frame_tag 'main' do%>


<%= form_with model: @event, data: {turbo_frame:"_top"} do |form| %>
<header>
  <h2 id="name">Edit Event</h2>
  </header>
<div class="form" >
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name%>
  
    <%= form.label :event_date, style: "display: block" %>
    <%= form.datetime_field :event_date %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
 
    <%= form.label :capacity, style: "display: block" %>
    <%= form.number_field :capacity %>
  </div>

  
</div>
 <div style="width:400px;margin:auto;">
    <%= form.label :message, style: "display: block" %>
    <%= form.text_area(:message ,size: 10) %>
  </div>

   <%= form.submit "Save Event"%>
   </div>
<% end %>


<%end%>

app/views/events/index.html.erb
  
  <div class="options">
    <h1>My Events</h1>
    <%=link_to "All Events", root_path, class:"contrast"%>
    <%=link_to "Upcoming Events", events_path(opt: 'upcoming'), class:"contrast"%>
    <%=link_to "Closed Events", events_path(opt: 'closed'), class:"contrast"%>
    

  </div>
  
  <%=turbo_frame_tag "events" do%>
<div class="events_cards" id="events_cards">
  <%if @events.exists?%>
  <%=turbo_stream_from :events_list%>
  <% @events.each do |event| %>
      <div id="events"  >
      <article id="event_<%=event.id%>" data-controller="hello">
        <!-- Card header-->

        <header>
          <div>
            <strong><%=event.name%></strong> 
            
                <div class="view_btn"> 
                    <%=link_to "View Event", event_path(event), data:{turbo_frame:"aside_detail", hello_target:"link"}%>         
             
                  <div class="copy_link" data-action="click->hello#copyLink">
                    <span class="material-symbols-outlined"> link </span> <small>Copy Link</small>
               </div>

               </div>

             

             </div>
          </header>

          <!---- card details-->
          <div class="grid card_details">


              <div class="details">
                <p class="info"><%=event.format_date%></p>
                <p class="info_name">Date</p>
             </div> 
               <div class="details ">
                <p class="info"><%=event.capacity%></p>
                <p class="info_name">Capacity</p>
             </div>



          </div>
          <!-- Card footer-->
             <footer>
              <div>
               <%if (event.return_progress && event.return_progress != 100) && event.available === true %>
                   <progress value="<%=event.return_progress%>"  max="100"/>
                 <%else%>
                   <!--<strong> Event Full</strong> -->
                   <div class="status" style="color:<%= (event.return_status == "Event Full") ? "#197622" : "#761919"%>;">
                   <%= event.return_status%>
                    </div>
                <%end%>
                </div>
              
              </footer>
        </article>
    </div>
  <% end %>
  <%else%>
  <div class="notice">
    <h1>Sorry, you don't have any events</h1>
    </div>
  <%end%>
</div>

<%= will_paginate @events, :page_links => false %>
<%end%>

app/views/events/new.html.erb
<%=turbo_frame_tag 'main' do%>


<%= form_with model: @event, data: {turbo_frame:"_top"} do |form| %>
<header>
  <h2 id="name">Add New Event</h2>
  </header>
<div class="form" >
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  
    <%= form.label :event_date, style: "display: block" %>
    <%= form.datetime_field :event_date %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
 
    <%= form.label :capacity, style: "display: block" %>
    <%= form.number_field :capacity %>
  </div>

  
</div>
 <div style="width:400px;margin:auto;">
    <%= form.label :message, style: "display: block" %>
    <%= form.text_area(:message ,size: 10) %>
  </div>

   <%= form.submit "Save Event"%>
   </div>
<% end %>


<%end%>

app/views/events/show.html.erb
<%=turbo_frame_tag 'aside_detail' do%>
<%=turbo_stream_from :event%>
<div class="event_detail">

      <article>
        <!-- Card header-->

        <header>
          <div>
            <h2 id="name"><%=@event.name%></h2>
             </div>
          </header>
           

          <!---- card details-->
          <div class="grid card_details" id="view_detail">


              <div class="details">
                <p class="info"><%=@event.format_date%></p>
                <p class="info_name">Date</p>
             </div> 
               <div class="details ">
                <p class="info"><%=@event.capacity%></p>
                <p class="info_name">Capacity</p>
             </div>

          </div>

           <hr>
           <%if @event.user == current_user%>
           <div class="options"style= "display:block;">
                
                <h2 style="margin-bottom:0px;"> <%=@event.progress%>%</h2>
                <span style="color: #767373;">Capacity at</span>

                  <div style="margin-top:20px;">
                <%=link_to "Check List Of Guests",event_guest_path(@event),data: {turbo_frame: 'main', action:"click->hello#open"}, class:"primary"%>
          </div>

          </div>
          <%elsif @event.available == false %>
            <div style="text-align:center; margin-bottom:30px;" >
            <span class="material-symbols-outlined red" style="font-size:70px;">
                                    event_busy
                                                  </span>
                <h3>SORRY, THE EVENT IS CLOSED</h3>
              </div>

           <%else%>
           <%=turbo_frame_tag "guest" do%>
           <div class="confirmation">
                <p> <%=(@event.message.empty?) ? "I would love, to have yoy in my party" : @event.message %></p>
                <small><%=link_to @event.address, @event.map_url,target:"_blank", style:"text-decoration:none;border:none;"%></small>
                <div class="confirmation_btn">
                  <%=link_to "I'LL BE THERE",new_event_guest_path(@event), class:"btn contrast"%>
                  </div>
            </div>
            <%end%>
            <%end%>

          <!-- Card footer-->
             <footer>
                 <div class="status" style="text-align:center;color:<%= (@event.return_status == "Event Full") ? "#197622" : "#761919"%>;">
                   <%= @event.return_status  if (current_user && current_user.id == @event.user.id)%>
                    </div>
              </footer>
        </article>
    </div>
    <%if @event.user == current_user%>
      <div class="options" style="width:auto;margin-top:0px;">

      <%= link_to  edit_event_path(@event),data:{turbo_frame:"main", action:"click->hello#open", tooltip:"Edit event"},style:"margin-right:5px;", class:"contrast" do%>
        <span class="material-symbols-outlined" style="padding:0px;">edit_square</span>
      <%end%> 

  <%= link_to  @event, data:{turbo_method: :delete, turbo_frame:"_top",tooltip:"Delete Event"}, class:"contrast" do %>
      <span class="material-symbols-outlined">
        delete
      </span>
     <%end%>
  </div>
<%end%>
</div>
<%end%>

app/views/guests/new.html.erb
<%=turbo_frame_tag "guest" do%>
<div class="guest_form">
    
<%=form_with model: ([@event, @event.guests.build]), data:{turbo_frame: "_top"} do |f|%>
  <div class="container">

    <div>
     <%=f.label "Your name"%>
    <%= f.text_field :name %>
    </div>

    <div>
      <%=f.label "Number of companions"%>
    <%= f.number_field :companions %>   
    </div>

    <%=f.submit "Confirm Participation"%>
</div>
<%end%>

</div>
<%end%>

app/views/guests/show.html.erb
  <%=turbo_frame_tag "main" do%>
  
   <table>
                <thead>
                  <tr>
                  <th scope="col">Guest Name</th>
                  <th scope="col">Companions </th>
                    </tr>
                  </thead>
                  <tbody> 
                     <%@guests.each do |g|%>
                    <tr>
                    
                      <th scope="row"><%=g.name%></th>
                      <td><%=g.companions%></td>
                      
                      </tr>

                     
                    
                      <%end%>
                        <tr>
                        <th scope="row" style="color:#197622;">Total of Guests</th> 
                        <td> <%=@event.return_total%></td>
                        
                        </tr>
                       
                    </tbody>
                </table>

<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CurrentEvent</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />   
    
    <style>
.material-symbols-outlined {
  font-variation-settings:
  'FILL' 0,
  'wght' 400,
  'GRAD' 0,
  'opsz' 20
}
</style>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   
    <!--Navigation-->
    <div class="app" data-controller="hello">
        <!--Navigation-->
        <%if user_signed_in?%>
        <div class="navigation">
        <aside>
        <nav>
          <ul>
            <li><%=link_to "My events ",root_path, class:"secondary"%></li>
              <li>
                <%=link_to "New Event", new_event_path,data: {turbo_frame: 'main', action:"click->hello#open"}, class:"secondary"%>
              </li>
               
            </ul>
          </nav>
          </aside>

          <div class="account">
            <div style="display:inline-block;">
              <span><%=link_to current_user.full_name,edit_user_registration_path, data:{turbo_frame: "main", action:"click->hello#open"},class:"contrast" %></span> 
              <%=link_to destroy_user_session_path, data:{turbo_method: :delete} do%>
              <span  style="margin-left:10px;float:right;font-weight:bold;"class="material-symbols-outlined">logout</span>
              <%end%>
              </div>
            </div>
        </div>
     <!--End Navigation-->

<!--Modal-->
      <dialog data-hello-target="modal">
        <article>
          <!--Modal Header-->
        <button data-action="click->hello#closeModal" aria-label="Close" rel="prev" class="close_btn"></button> 
       

        <!--Modal Content-->
        <div style="height:600px;">
        <%=turbo_frame_tag 'main'%>
        </div>
        </article>
        </dialog>
        <!--End Modal-->


          <!--Fetch body from rails-->
    <div class="body_fetch">
    <%= yield %>
      </div>

    <div class="aside_detail">
      <div class="turbo">
        <%=turbo_frame_tag "aside_detail" %>
      </div>
      <%else%>
       <div class="body_fetch">
      <%=yield%>
      </div>
      <%end%>
   
 </div>
  

    </div>
  </body>
</html>